# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-10 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='blurb',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
